[WIP] Build iconographer as a tarball
hodefoting/iconographer pull request #5
Opened 2017-01-16 19:41 UTC by GabiThume

2017-01-24 19:36 UTC, automata commented
It's also being built/deployed from Heroku too: https://travis-ci.org/the-grid/iconographer/builds/194928441#L5579.

2017-01-25 20:39 UTC, jonnor commented on upload-to-s3.sh
> +  echo "Amazon API Token not provided, skipping upload";
Why not fail hard? If you don't want to upload something, probably should not call an upload script?

2017-01-25 20:40 UTC, jonnor commented on Makefile
> +CFLAGS += -funroll-loops -fforce-addr -ftracer -fpeel-loops -fmerge-all-constants
Where do these CFLAGS come from and why are they important?

2017-01-25 20:41 UTC, jonnor commented on Makefile
> +CFLAGS += -funroll-loops -fforce-addr -ftracer -fpeel-loops -fmerge-all-constants
Nevermind, I see they were in the original Makefiles. I guess we keep them then.

2017-01-25 20:41 UTC, jonnor commented on .travis.yml
> +language: c
Yay continious integration

2017-01-25 20:42 UTC, jonnor commented on .travis.yml
> +- make release-and-upload VERSION=`git describe --tags` TARGET=travis-${TRAVIS_OS_NAME}
This should call a `check` or `release-check` target. Upload should be separate.

2017-01-25 20:43 UTC, jonnor requested changes
Should change upload logic to be only on deploy.

2017-01-26 18:02 UTC, automata commented
@jonnor thanks for the suggestions. Can you take a look again, pls? I'll remove 8b85e40 before merging, that was just to conveniently check deploy from this PR.

2017-01-26 19:27 UTC, jonnor approved these changes

2017-01-26 19:27 UTC, merged